version: '3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.0
    container_name: kibana
    environment:
        SERVER_NAME: kibana-docker
        ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
        - "5601:5601"
    networks:
      - elastic
    depends_on:
      - es01

  apm:
    build:
        context: apm/
    container_name: apm
    ports:
        - "8200:8200"
    networks:
        - elastic
    depends_on:
        - es01

networks:
    elastic:
        driver: bridge